spring:
  datasource:
    url: jdbc:mysql://10.0.0.78:3306/ems-sys
    username: root
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.0.0.78:8081/realms/erp-realm
          jwk-set-uri: http://10.0.0.78:8081/realms/erp-realm/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: 10.0.0.78:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  error:
    include-message: always